const express = require('express');
const multer  = require('multer');
const path    = require('path');
const fs      = require('fs');

const app  = express();
const PORT = 3000;

// Serve the whole project as static files
app.use(express.static(__dirname));
app.use(express.json());

// Multer: store uploads in memory, we move them ourselves
const upload = multer({ storage: multer.memoryStorage() });

// All multipart field names used across add and edit
const UPLOAD_FIELDS = [
  { name: 'homePageImage',     maxCount: 1  },
  { name: 'detailIcon',        maxCount: 1  },
  { name: 'descriptionBanner', maxCount: 1  },
  { name: 'screenshots',       maxCount: 10 },
  { name: 'apkFile',           maxCount: 1  }
];

// ── Helpers ────────────────────────────────────────────────

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, { recursive: true });
}

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function saveFile(buffer, destPath) {
  ensureDir(path.dirname(destPath));
  fs.writeFileSync(destPath, buffer);
}

function readCurrentApps() {
  const dataPath = path.join(__dirname, 'app-data.js');
  const content  = fs.readFileSync(dataPath, 'utf8');
  const match    = content.match(/const ALL_APPS\s*=\s*(\[[\s\S]*?\]);/);
  if (!match) return [];
  try {
    // eslint-disable-next-line no-new-func
    const arr = new Function(`return ${match[1]}`)();
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

function writeAppData(apps) {
  const dataPath = path.join(__dirname, 'app-data.js');

  const entries = apps.map(app => {
    const screenshots = app.screenshots && app.screenshots.length
      ? `[\n      ${app.screenshots.map(s => `"${s}"`).join(',\n      ')}\n    ]`
      : '[]';

    return `  {
    id:               "${app.id}",
    appName:          "${app.appName}",
    developer:        "${app.developer}",
    type:             "${app.type}",
    rating:           ${app.rating},
    reviews:          ${app.reviews || 0},
    version:          "${app.version}",
    size:             "${app.size || ''}",
    lastUpdated:      "${app.lastUpdated}",
    minAndroid:       "${app.minAndroid}",
    description:      ${JSON.stringify(app.description)},
    shortDescription: ${JSON.stringify(app.shortDescription)},
    homePageImage:    "${app.homePageImage}",
    detailIcon:       "${app.detailIcon}",
    descriptionBanner:"${app.descriptionBanner}",
    screenshots:      ${screenshots},
    apkFile:          "${app.apkFile}",
    featured:         ${app.featured},
    playStoreLink:    ${JSON.stringify(app.playStoreLink || '')}
  }`;
  });

  const fileContent = `// ============================================================
//  app-data.js — ALL_APPS Array
//  AppVault Play Store
//
//  AUTO-GENERATED by admin-server.js
//  Add / edit apps via http://localhost:${PORT}/admin.html
// ============================================================

const ALL_APPS = [
${entries.join(',\n\n')}
];
`;

  fs.writeFileSync(dataPath, fileContent, 'utf8');
}

// ════════════════════════════════════════════════════════════
//  POST /api/add-app
// ════════════════════════════════════════════════════════════
app.post('/api/add-app', upload.fields(UPLOAD_FIELDS), (req, res) => {
  try {
    const body     = req.body;
    const existing = readCurrentApps();

    // Build unique slug ID
    const baseId = slugify(body.appName || 'app');
    let appId    = baseId;
    let counter  = 2;
    while (existing.find(a => a.id === appId)) appId = `${baseId}-${counter++}`;

    const appImgDir     = path.join(__dirname, 'appsImages', appId);
    const screenshotDir = path.join(appImgDir, 'screenshots');
    const apkDir        = path.join(__dirname, 'AllApk');

    ensureDir(appImgDir);
    ensureDir(screenshotDir);
    ensureDir(apkDir);

    // Home card image
    let homePageImagePath = `appsImages/${appId}/home-card-image.png`;
    if (req.files['homePageImage']) {
      const file = req.files['homePageImage'][0];
      const ext  = path.extname(file.originalname) || '.png';
      homePageImagePath = `appsImages/${appId}/home-card-image${ext}`;
      saveFile(file.buffer, path.join(__dirname, homePageImagePath));
    }

    // App icon
    let detailIconPath = `appsImages/${appId}/detail-icon.png`;
    if (req.files['detailIcon']) {
      const file = req.files['detailIcon'][0];
      const ext  = path.extname(file.originalname) || '.png';
      detailIconPath = `appsImages/${appId}/detail-icon${ext}`;
      saveFile(file.buffer, path.join(__dirname, detailIconPath));
    }

    // Description banner
    let descriptionBannerPath = `appsImages/${appId}/description-banner.png`;
    if (req.files['descriptionBanner']) {
      const file = req.files['descriptionBanner'][0];
      const ext  = path.extname(file.originalname) || '.png';
      descriptionBannerPath = `appsImages/${appId}/description-banner${ext}`;
      saveFile(file.buffer, path.join(__dirname, descriptionBannerPath));
    }

    // Screenshots
    const screenshotPaths = [];
    if (req.files['screenshots']) {
      req.files['screenshots'].forEach((file, i) => {
        const ext     = path.extname(file.originalname) || '.png';
        const relPath = `appsImages/${appId}/screenshots/screen-${i + 1}${ext}`;
        saveFile(file.buffer, path.join(__dirname, relPath));
        screenshotPaths.push(relPath);
      });
    }

    // APK
    let apkFilePath = '';
    if (req.files['apkFile']) {
      const file  = req.files['apkFile'][0];
      apkFilePath = `AllApk/${appId}.apk`;
      saveFile(file.buffer, path.join(__dirname, apkFilePath));
    }

    const newApp = {
      id:               appId,
      appName:          body.appName          || '',
      developer:        body.developer        || '',
      type:             body.type             || 'App',
      rating:           parseFloat(body.rating) || 5,
      reviews:          parseInt(body.reviews)  || 0,
      version:          body.version          || '1.0.0',
      size:             body.size             || '',
      lastUpdated:      body.lastUpdated      || new Date().toISOString().split('T')[0],
      minAndroid:       body.minAndroid       || '5.0',
      description:      body.description      || '',
      shortDescription: body.shortDescription || '',
      homePageImage:    homePageImagePath,
      detailIcon:       detailIconPath,
      descriptionBanner:descriptionBannerPath,
      screenshots:      screenshotPaths,
      apkFile:          apkFilePath,
      featured:         body.featured === 'true',
      playStoreLink:    body.playStoreLink    || ''
    };

    existing.push(newApp);
    writeAppData(existing);

    res.json({ success: true, message: `App "${newApp.appName}" added successfully!`, appId, app: newApp });

  } catch (err) {
    console.error('Error adding app:', err);
    res.status(500).json({ success: false, message: `Error: ${err.message}` });
  }
});

// ════════════════════════════════════════════════════════════
//  POST /api/edit-app
//  Updates text fields and optionally replaces files.
//  Files not sent = keep existing paths.
// ════════════════════════════════════════════════════════════
app.post('/api/edit-app', upload.fields(UPLOAD_FIELDS), (req, res) => {
  try {
    const body     = req.body;
    const appId    = body.appId;

    if (!appId) return res.status(400).json({ success: false, message: 'No appId provided.' });

    const existing = readCurrentApps();
    const idx      = existing.findIndex(a => a.id === appId);

    if (idx === -1) return res.status(404).json({ success: false, message: `App "${appId}" not found.` });

    const current = existing[idx];

    // ── Replace image files only if new ones were uploaded ──

    let homePageImagePath = current.homePageImage;
    if (req.files['homePageImage']) {
      const file = req.files['homePageImage'][0];
      const ext  = path.extname(file.originalname) || '.png';
      homePageImagePath = `appsImages/${appId}/home-card-image${ext}`;
      saveFile(file.buffer, path.join(__dirname, homePageImagePath));
    }

    let detailIconPath = current.detailIcon;
    if (req.files['detailIcon']) {
      const file = req.files['detailIcon'][0];
      const ext  = path.extname(file.originalname) || '.png';
      detailIconPath = `appsImages/${appId}/detail-icon${ext}`;
      saveFile(file.buffer, path.join(__dirname, detailIconPath));
    }

    let descriptionBannerPath = current.descriptionBanner;
    if (req.files['descriptionBanner']) {
      const file = req.files['descriptionBanner'][0];
      const ext  = path.extname(file.originalname) || '.png';
      descriptionBannerPath = `appsImages/${appId}/description-banner${ext}`;
      saveFile(file.buffer, path.join(__dirname, descriptionBannerPath));
    }

    // Screenshots: only replace if new ones uploaded, otherwise keep existing
    let screenshotPaths = current.screenshots || [];
    if (req.files['screenshots'] && req.files['screenshots'].length > 0) {
      const screenshotDir = path.join(__dirname, 'appsImages', appId, 'screenshots');
      ensureDir(screenshotDir);
      screenshotPaths = [];
      req.files['screenshots'].forEach((file, i) => {
        const ext     = path.extname(file.originalname) || '.png';
        const relPath = `appsImages/${appId}/screenshots/screen-${i + 1}${ext}`;
        saveFile(file.buffer, path.join(__dirname, relPath));
        screenshotPaths.push(relPath);
      });
    }

    // APK: keep existing if nothing uploaded
    let apkFilePath = current.apkFile;
    if (req.files['apkFile']) {
      const file  = req.files['apkFile'][0];
      apkFilePath = `AllApk/${appId}.apk`;
      saveFile(file.buffer, path.join(__dirname, apkFilePath));
    }

    // ── Merge updated fields onto existing app object ───────
    const updatedApp = {
      ...current,
      appName:          body.appName          || current.appName,
      developer:        body.developer        || current.developer,
      type:             body.type             || current.type,
      rating:           parseFloat(body.rating) || current.rating,
      version:          body.version          || current.version,
      size:             body.size             || current.size,
      lastUpdated:      body.lastUpdated      || current.lastUpdated,
      minAndroid:       body.minAndroid       || current.minAndroid,
      description:      body.description      !== undefined ? body.description      : current.description,
      shortDescription: body.shortDescription !== undefined ? body.shortDescription : current.shortDescription,
      playStoreLink:    body.playStoreLink    !== undefined ? body.playStoreLink    : (current.playStoreLink || ''),
      featured:         body.featured === 'true',
      homePageImage:    homePageImagePath,
      detailIcon:       detailIconPath,
      descriptionBanner:descriptionBannerPath,
      screenshots:      screenshotPaths,
      apkFile:          apkFilePath
    };

    existing[idx] = updatedApp;
    writeAppData(existing);

    res.json({ success: true, message: `App "${updatedApp.appName}" updated successfully!`, app: updatedApp });

  } catch (err) {
    console.error('Error editing app:', err);
    res.status(500).json({ success: false, message: `Error: ${err.message}` });
  }
});

// ════════════════════════════════════════════════════════════
//  POST /api/delete-app
// ════════════════════════════════════════════════════════════
app.post('/api/delete-app', express.json(), (req, res) => {
  try {
    const { appId } = req.body;
    if (!appId) return res.status(400).json({ success: false, message: 'No appId provided.' });

    const existing = readCurrentApps();
    const filtered = existing.filter(a => a.id !== appId);

    if (filtered.length === existing.length) {
      return res.status(404).json({ success: false, message: 'App not found.' });
    }

    writeAppData(filtered);
    res.json({ success: true, message: `App "${appId}" removed from list.` });

  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// ════════════════════════════════════════════════════════════
//  GET /api/apps
// ════════════════════════════════════════════════════════════
app.get('/api/apps', (req, res) => {
  try {
    res.json({ success: true, apps: readCurrentApps() });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// ── Start server ────────────────────────────────────────────
app.listen(PORT, () => {
  console.log('');
  console.log('  AppVault Admin Server');
  console.log(`  Admin  ->  http://localhost:${PORT}/admin.html`);
  console.log(`  Site   ->  http://localhost:${PORT}/`);
  console.log('  Ctrl+C to stop');
  console.log('');
});