// ============================================================
//  app-data.js — ALL_APPS Array
//  AppVault Play Store
//
//  AUTO-GENERATED by admin-server.js
//  Add / edit apps via http://localhost:3000/admin.html
// ============================================================

const ALL_APPS = [
  {
    id:               "safe-circle",
    appName:          "Safe Circle Test 2",
    developer:        "Robin Kumar",
    type:             "Tools",
    rating:           5,
    reviews:          0,
    version:          "1.2.1",
    size:             "16.4 MB",
    lastUpdated:      "2026-04-29",
    minAndroid:       "21.0",
    description:      "Safe Circle is a family and friends safety app designed to keep your loved ones secure and connected at all times. With Safe Circle, you can create multiple groups and invite people to join, allowing everyone in the group to share their real-time location easily and privately.\r\n\r\nThis app helps you know where your family members and friends are, giving you peace of mind and ensuring their safety. Whether it’s daily check-ins or emergency situations, Safe Circle provides reliable real-time tracking so you can act quickly if someone is in trouble.\r\n\r\nKey Features:\r\n\r\nCreate and manage multiple groups for family, friends, or any community.\r\n\r\nReal-time location sharing within groups for continuous safety monitoring.\r\n\r\nQuick and easy group joining through invitations.\r\n\r\nDesigned with privacy and security in mind; location data is shared only with trusted group members.\r\n\r\nEfficient activity recognition triggers location updates to save battery while ensuring accurate tracking.\r\n\r\nNo need for passwords or complicated logins — sign in securely with your Google account.\r\n\r\nSafe Circle is perfect for families, friends, caregivers, and anyone who values safety and staying connected. Download now to protect what matters most!\r\n",
    shortDescription: "Safety starts with understanding how developers collect and share your data.",
    homePageImage:    "appsImages/safe-circle/home-card-image.png",
    detailIcon:       "appsImages/safe-circle/detail-icon.webp",
    descriptionBanner:"appsImages/safe-circle/description-banner.png",
    screenshots:      [
      "appsImages/safe-circle/screenshots/screen-1.webp",
      "appsImages/safe-circle/screenshots/screen-2.webp",
      "appsImages/safe-circle/screenshots/screen-3.webp",
      "appsImages/safe-circle/screenshots/screen-4.webp",
      "appsImages/safe-circle/screenshots/screen-5.webp",
      "appsImages/safe-circle/screenshots/screen-6.webp"
    ],
    apkFile:          "AllApk/safe-circle.apk",
    featured:         true,
    playStoreLink:    "https://play.google.com/store/apps/details?id=com.kgjr.safecircle"
  }
];
